In [4]:
# Python Array Module
import array as myarray


# TypeCodes Available for the array module for various data types

* 'I' - Integer type - 2
* 'f' - Float type - 4
* 'd' - Float type - 8
* 'u' - unicode character - 2
* For more details - visit https://docs.python.org/3/library/arrayhtml

In [5]:
#creating an array
arr = myarray.array('i', [1,2,3])
arr1 = myarray.array('d', [1.0, 2.1, 2.4, 2.5, 2.6])
arr2 = myarray.array('u', ['a', 'b', 'c', 'd'])

#typecodes
print(arr.typecode)
print(arr1.typecode)
print(arr2.typecode)
#looking at the array
print(arr)
print(arr1)
print(arr2)

i
d
u
array('i', [1, 2, 3])
array('d', [1.0, 2.1, 2.4, 2.5, 2.6])
array('u', 'abcd')


C:\Users\Personal PC\AppData\Local\Temp\ipykernel_13636\15740046.py:4: DeprecationWarning: The 'u' type code is deprecated and will be removed in Python 3.16
  arr2 = myarray.array('u', ['a', 'b', 'c', 'd'])


In [6]:
# find the lengh of an array
print(len(arr))
print(len(arr1))
print(len(arr2))

3
5
4


In [7]:
for i in range (0, len(arr)):
    print(arr[i], end=" ")
print("\n")

for i in range (0, len(arr1)):
    print(arr1[i], end=" ")
print("\n")

for i in range (0, len(arr2)):
    print(arr2[i], end=" ")
print("\n")


1 2 3 

1.0 2.1 2.4 2.5 2.6 

a b c d 



#What is indexing?
* For any array of the length n, the indexing will be the position at which each element is placed in an array. To be able to access the elements in an array, indexing comes in handy. For an array of length n, the indexing will start from 0 and end at n-1.

In [8]:
#Assessing elements from an Array using index values:
x = list(range(1,100,2))
new_array = myarray.array('i', x)

#printing the array
for i in range(0, len(new_array)):
    print(new_array[i], end=" ")
print("\n") 

#Assessing element at index "25"
print(new_array[25])

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99 

51


In [9]:
print(len(x))

50


In [10]:
#additional eg.

y = list(range(1, len(x), 10))
new_array2=myarray.array('i',y)
for i in range(0, len(new_array2)):
    print(new_array2[i], end=" ")

1 11 21 31 41 

In [11]:
#Adding Elements in an Array:
new_arr = myarray.array('i', [3,4,5,6,7,9,10])
for i in range(0, len(new_arr)):
    print(new_arr[i], end=" ")
print(end="\n")    

#adding elements in the array:
new_arr.insert(0,2)
new_arr.insert(0,1)

#printing the new array
for i in range(0, len(new_arr)):
    print(new_arr[i], end=" ")
print(end="\n")    

#using append
new_arr.append(11)
for i in range(0, len(new_arr)):
    print(new_arr[i], end=" ")


3 4 5 6 7 9 10 
1 2 3 4 5 6 7 9 10 
1 2 3 4 5 6 7 9 10 11 

In [12]:
#Updating elements in an array
new_arrays= myarray.array('i', [1, 2, 2, 4, 5])

#printing array
for i in range(0, len(new_arrays)):
    print(new_arrays[i], end=" ")
print("\n")

#updating the array
new_arrays[3] = 30 # assigned new value at index 2
for i in range(0, len(new_arrays)):
    print(new_arrays[i], end=" ")

1 2 2 4 5 

1 2 2 30 5 

In [13]:
#deleting elements in an array:
new_arrays.pop(4)

for i in range(0, len(new_arrays)):
    print(new_arrays[i], end=" ")

1 2 2 30 

In [14]:
#using the remove() method
new_arrays.remove(2)
for i in range(0, len(new_arrays)):
    print(new_arrays[i], end=" ")

1 2 30 

# Slicing
* Slicing is the process of getting a sequence from the data structure which will have a starting index and an ending index. Since, python arrays provide indexing, slicing operations provide extensive usage of arrays.

In [15]:
#slicing operations in a array
x = list(range(0,100,3))
arr = myarray.array('i', x)

#slicing operations
arr0 = arr[10:20]
for i in range(0, len(arr0)):
    print(arr0[i], end=" ")
print("\n")    

#negative indexing
arr1 = arr[10:-10]
for i in range(0, len(arr1)):
    print(arr1[i], end=" ")
print("\n") 

#reversing the order using slicing
arr2 = arr[::-1]
for i in range(0, len(arr2)):
    print(arr2[i], end=" ")



30 33 36 39 42 45 48 51 54 57 

30 33 36 39 42 45 48 51 54 57 60 63 66 69 

99 96 93 90 87 84 81 78 75 72 69 66 63 60 57 54 51 48 45 42 39 36 33 30 27 24 21 18 15 12 9 6 3 0 

In [16]:
# Searching operations in an array using index()
x = list(range(0, 1000000, 2))
search_array = myarray.array('i', x)

#print first 10 elements of the array
for i in range(0, len(search_array[0:10])):
    print(search_array[i], end=" ")
print(end="\n")

#search the number 10002 in the array
index = search_array.index(10002)
res = search_array[index]
print(index, res)

0 2 4 6 8 10 12 14 16 18 
5001 10002


In [17]:
#sorting operations
sort_array = myarray.array('i', [5,3,4,6,9,7,8])
sorted_array = sort_array.tolist()

#ascending order
sorted_array.sort()
print(sorted_array)

#descending order
sorted_array.sort(reverse=True)
print(sorted_array)

[3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3]


# Numpy Arrays

In [18]:
#numpy arrays
#creating numpy arrays
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print("\n")

#creating an array with all zeros
zeros = np.zeros((2,2))
#creating an array with all ones 
ones = np.ones((2,2))
#creating an array with constent values
const = np.full((2,2), 5)
#creating an identity matrix
iden = np.eye(2)
#creating an array with random values
random = np.random.random((2,3))

print(zeros) 
print("\n")
print(ones)
print("\n")
print(const)
print("\n")
print(iden)
print("\n")
print(random)

[1 2 3 4 5]


[[0. 0.]
 [0. 0.]]


[[1. 1.]
 [1. 1.]]


[[5 5]
 [5 5]]


[[1. 0.]
 [0. 1.]]


[[0.99386345 0.64457099 0.21035481]
 [0.02681672 0.69753354 0.15507302]]


In [19]:
#1-D, 2-D, 3-D Numpy Arrays
#0-Dimensional array
zerod = np.array(1)
print(zerod)
print('\n')
#1-Dimensional array
oned= np.array([1,1])
print(oned)
print('\n')
#2-Dimensional array
twoed= np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(twoed)
print('\n')
#3-Dimensional array
threed= np.array([[[1,2,3],[3,4,5]], [[5,6,7],[7,8,9]]])
print(threed)
print('\n')

#Multi-Dimensional array
multid= np.array([1,2,3,4,5], ndmin=7)
print(multid)


1


[1 1]


[[1 2 3 4 5]
 [1 2 3 4 5]]


[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]


[[[[[[[1 2 3 4 5]]]]]]]


In [20]:
print(zerod.ndim)
print(oned.ndim)
print(twoed.ndim)
print(threed.ndim)
print(multid.ndim)

0
1
2
3
7


In [21]:
#CRUD Operations in Numpy Arrays
#reading from a numpy array
sample_array = np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(0, len(sample_array)):
    print(sample_array[i], end=" ")
print(end="\n")

#updating elements in a numpy array, we make use of indexing here.
sample_array[9] = 100
print(sample_array)

#deleting elements in a numpy array
sample_array = np.delete(sample_array, 9)
print(sample_array) 

1 2 3 4 5 6 7 8 9 10 
[  1   2   3   4   5   6   7   8   9 100]
[1 2 3 4 5 6 7 8 9]


In [22]:
#searching elements in a numpy array
x = list(range(0,20000, 5))
sample_search_array = np.array(x)
#searching the element 5500
res = np.where(sample_search_array == 5500)
print(res)
#checking if the routine index is true
print(sample_search_array[1100])

(array([1100]),)
5500


In [23]:
#sorting elements in a numpy array
sample_sort_array = np.array([1,4,9,2,3,8,7,6])
#sorting the numpy array using sort()
x = np.sort(sample_sort_array)
print(x)

[1 2 3 4 6 7 8 9]


In [26]:
#mathematical operations on numpy arrays
a = np.array([[1,2,3]], dtype = np.int64)
b = np.array([[4,5,6]], dtype = np.int64)
#adding two numpy arrays
addition = np.add(a,b)
print(addition)
print(end="\n")
#subtracting two numpy arrays
subtraction = np.subtract(a,b)
print(subtraction)
print(end="\n")
#multiplying two numpy arrays
multiply = np.multiply(a,b)
print(multiply)
print(end="\n")
#dividing two numpy arrays
divide = np.divide(a,b)
print(divide)
print(end="\n")
#square root of two numpy arrays
sqrt = np.sqrt(a)
sqrt2 = np.sqrt(b)
print(sqrt)
print(sqrt2)
print(end="\n")
#transpose of a numpy array
x = np.array([[1,2,3], [1,2,3], [1,2,3]])
transpose = np.transpose(x)
print(x)
print("\n")
print(transpose)

[[5 7 9]]

[[-3 -3 -3]]

[[ 4 10 18]]

[[0.25 0.4  0.5 ]]

[[1.         1.41421356 1.73205081]]
[[2.         2.23606798 2.44948974]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]


[[1 1 1]
 [2 2 2]
 [3 3 3]]
