In [2]:
import numpy as np

In [3]:
myarr = np.array([[3,6,32,7]], np.int8)

In [4]:
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr[0]

array([ 3,  6, 32,  7], dtype=int8)

In [7]:
myarr[0, 1]

np.int8(6)

In [8]:
myarr.dtype

dtype('int8')

In [9]:
myarr[0, 1] = 45

In [10]:
myarr

array([[ 3, 45, 32,  7]], dtype=int8)

# 1. Array creation: Conversion from other Python structures (eg. lists, tupples)

In [11]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [12]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [13]:
listarray.dtype

dtype('int64')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

# 2. Intrinsic numpy array creation objects (eg. arrange, ones, zeros, etc.)

In [16]:
zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1,5,12) # 1st eg

In [21]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
lspace = np.linspace(1,4,4) #2nd eg

In [23]:
lspace

array([1., 2., 3., 4.])

In [24]:
emp = np.empty((4,6))

In [25]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.60219035e-306, 7.56599807e-307, 2.11395597e-307],
       [1.42419938e-306, 7.56603881e-307, 7.56600486e-307,
        1.02360867e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307, 6.23059726e-307],
       [1.42419530e-306, 7.56589622e-307, 2.22520559e-306,
        1.11261298e-306, 9.79107193e-307, 2.22522596e-306]])

In [26]:
emp_like = np.empty_like(lspace)

In [27]:
emp_like

array([1., 2., 3., 4.])

In [28]:
ide = np.identity(45)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr = arr.reshape(3, 33)

In [33]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
arr = arr.ravel() # will arrange in 1d array

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.shape

(99,)

# Numpy Axis

In [37]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [38]:
ar = np.array(x)

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar.sum(axis=0)

array([12,  8,  9])

In [41]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [42]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [43]:
ar.flat

In [44]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [45]:
ar.ndim # no. of dimensions

2

In [46]:
ar.size # no. of elements

9

In [47]:
ar.nbytes

72

In [48]:
one = np.array([1,3,4,634,2])

In [49]:
one.argmax()

np.int64(3)

In [50]:
one.argmin()

np.int64(0)

In [51]:
one.argsort()

array([0, 4, 1, 2, 3])

In [52]:
ar.argmax(axis=1)

array([2, 2, 0])

In [53]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [54]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [55]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [56]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [57]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [58]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [59]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

# Matrix calculations

In [60]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [61]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [62]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [63]:
ar.sum()

np.int64(29)

In [64]:
ar.max()

np.int64(7)

In [65]:
ar.min()

np.int64(0)

In [66]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [68]:
type(np.where(ar>5)) # returns the tuple of arrays

tuple

In [69]:
np.count_nonzero(ar)

np.int64(8)

In [70]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [71]:
ar[1,2] = 0

In [72]:
np.nonzero(ar) # shows the non zero elements in each axis

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [73]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 1, 0]])

# Numpy space occupancy comparision with python_array

In [74]:
import sys

In [75]:
py_ar = [0, 4, 55, 2]

In [76]:
np_ar = np.array(py_ar)

In [77]:
sys.getsizeof(1) * len(py_ar) # python array size occupancy

112

In [78]:
np_ar.itemsize * np_ar.size # numpy array size occupancy

32

In [79]:
(32/112)*100 # less than 1/3 is occupied by numpy

28.57142857142857

In [80]:
np_ar.tolist()

[0, 4, 55, 2]